
AWSTemplateFormatVersion: '2010-09-09'
Description: Simple S3 bucket stack

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test

  MySecondS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: test1
